version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
      - ./sсhema.sql:/docker-entrypoint-initdb.d/sсhema.sql
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    command: postgres -c 'log_statement=all'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      retries: 5
    restart: always
