CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    owner_id BIGINT NOT NULL,
    is_available BOOLEAN NOT NULL,
    request_id VARCHAR(512),
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES users(id)
    );

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(2000) NOT NULL,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL
);

CREATE INDEX index_name ON items(name);
CREATE INDEX index_description ON items(description);
CREATE INDEX bookings_start ON bookings(start_date);
CREATE INDEX bookings_end ON bookings(end_date);
CREATE INDEX bookings_item ON bookings(item_id);
CREATE INDEX bookings_user ON bookings(user_id);
CREATE INDEX bookings_id ON bookings(id);
CREATE INDEX comments_id ON comments(id);
CREATE INDEX items_id ON items(id);
